// src/lib/admin-settings-index.ts
//
// Static catalog of every Sir-only setting / control across `/admin/*`
// sub-pages. Drives the settings search on the admin landing — the
// shape mirrors a Windows / Android Settings search index: an entry
// per actionable control, not per record.
//
// Constants module — no `'use server'`. Imported by the client
// component `<AdminSettingsSearch>` and rendered offline (no Redis
// roundtrip). When you add a new setting / repair tool / admin
// surface, add an entry here too.

import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  Award,
  BarChart3,
  Bell,
  CalendarHeart,
  CalendarX,
  Clock,
  Database,
  Download,
  Eraser,
  FileText,
  Filter,
  FlaskConical,
  Gauge,
  Gift,
  HeartPulse,
  KeyRound,
  Logs as LogsIcon,
  Pin,
  RefreshCw,
  ScrollText,
  Send,
  Server,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Smartphone,
  Smile,
  Sparkles,
  Sun,
  Target,
  Timer,
  Trash2,
  Trophy,
  Wand2,
  Wrench,
  ZapOff,
} from "lucide-react";

export interface AdminSettingEntry {
  /** Stable id — used as React key + click telemetry handle. */
  id: string;
  /** Headline. Always shown; ranks highest in match score. */
  title: string;
  /** One-line gloss. Shown under the title; medium match weight. */
  description: string;
  /** Top-level admin page label, e.g. "Diagnostics". */
  page: string;
  /** Optional path inside the page, e.g. "Health · Repair operations". */
  section?: string;
  /** Where the result navigates. Hash anchors are best-effort. */
  href: string;
  /** Synonyms / alternate phrasings to match on. Lowercase, space-sep. */
  keywords: string;
  /** Icon for the result row. */
  Icon: LucideIcon;
}

// ── Settings catalog ──────────────────────────────────────────────────────
//
// Entries are grouped by destination page in the source for readability.
// Order within a group is roughly tab-order on the destination page.
// `keywords` is a free-form lowercase grab-bag for fuzzy matches —
// include redis key shapes, common synonyms, and known acronyms.

export const ADMIN_SETTINGS: AdminSettingEntry[] = [
  // ── /admin/stats ────────────────────────────────────────────────────────
  {
    id: "stats:counts",
    title: "Counts overview",
    description: "Per-feature record counts and totals.",
    page: "Stats",
    href: "/admin/stats",
    keywords: "stats counts ratios totals dashboard",
    Icon: BarChart3,
  },
  {
    id: "stats:heatmap",
    title: "30-day activity heatmap",
    description: "Daily activity intensity across the last 30 days.",
    page: "Stats",
    href: "/admin/stats",
    keywords: "heatmap activity calendar 30 days streak",
    Icon: BarChart3,
  },

  // ── /admin/health (Health tab) ─────────────────────────────────────────
  {
    id: "health:redis",
    title: "Redis connection",
    description: "Upstash latency probe + reachability check.",
    page: "Diagnostics",
    section: "Health",
    href: "/admin/health",
    keywords: "redis upstash latency connection ping health probe",
    Icon: Database,
  },
  {
    id: "health:fcm-creds",
    title: "FCM credentials check",
    description: "Verifies FIREBASE_PROJECT_ID / CLIENT_EMAIL / PRIVATE_KEY are set.",
    page: "Diagnostics",
    section: "Health",
    href: "/admin/health",
    keywords: "fcm firebase push credentials env environment vars",
    Icon: Bell,
  },
  {
    id: "health:fcm-tokens",
    title: "FCM tokens per author",
    description: "Multi-device count from push:fcm:{author} SET (Besho's phone + tablet land in the same set).",
    page: "Diagnostics",
    section: "Health",
    href: "/admin/health",
    keywords: "fcm token push notification registered daddy kitten count multi device set",
    Icon: Bell,
  },
  {
    id: "health:cron-secret",
    title: "CRON_SECRET status",
    description: "Without it every /api/cron/* returns 401 silently.",
    page: "Diagnostics",
    section: "Health",
    href: "/admin/health",
    keywords: "cron secret bearer auth cron-job 401",
    Icon: KeyRound,
  },
  {
    id: "health:cron-runs",
    title: "Cron last runs",
    description: "Telemetry per cron route — fresh / stale / error.",
    page: "Diagnostics",
    section: "Health",
    href: "/admin/health",
    keywords: "cron telemetry last run obedience-sweep ritual-windows review-window-open heartbeat-watch fresh stale",
    Icon: Clock,
  },
  {
    id: "health:time-integrity",
    title: "Time integrity",
    description: "Cairo offset, hours-into-day, day length sanity checks.",
    page: "Diagnostics",
    section: "Health",
    href: "/admin/health",
    keywords: "time cairo offset dst eet eest icu day length integrity",
    Icon: Sun,
  },
  {
    id: "health:notes-integrity",
    title: "Notes index integrity",
    description: "notes:index size + per-author stored vs expected counts + pinned size.",
    page: "Diagnostics",
    section: "Health",
    href: "/admin/health",
    keywords: "notes index integrity count drift pinned",
    Icon: FileText,
  },
  {
    id: "health:severities",
    title: "Recent severities (24h)",
    description: "Errors + warnings logged in the last 24h.",
    page: "Diagnostics",
    section: "Health",
    href: "/admin/health",
    keywords: "errors warnings severity activity log 24h",
    Icon: ShieldAlert,
  },

  // ── /admin/health → Repair operations ──────────────────────────────────
  {
    id: "repair:notes-counts",
    title: "Reseed notes counts + pinned",
    description: "Recompute notes:count:{author} from notes:index; prune stale notes:pinned members.",
    page: "Diagnostics",
    section: "Health · Repair operations · Index integrity",
    href: "/admin/health",
    keywords: "repair notes count pinned reseed index drift",
    Icon: Wrench,
  },
  {
    id: "repair:feature-indexes",
    title: "Reconcile feature indexes",
    description: "Walks every {feature}:index ZSET; drops members whose backing record is missing.",
    page: "Diagnostics",
    section: "Health · Repair operations · Index integrity",
    href: "/admin/health",
    keywords: "repair reconcile index zset drift orphan tasks rules ledger permissions rituals milestones timeline notes",
    Icon: Database,
  },
  {
    id: "repair:pending-claims",
    title: "Reconcile pending reward claims",
    description: "Drops decided-or-missing entries from rewards:claims:pending.",
    page: "Diagnostics",
    section: "Health · Repair operations · Index integrity",
    href: "/admin/health",
    keywords: "repair reward claims pending stale nudge zset reconcile",
    Icon: Gift,
  },
  {
    id: "repair:orphaned-reactions",
    title: "Prune orphaned reactions",
    description: "DELs reactions:{noteId} whose underlying note is gone.",
    page: "Diagnostics",
    section: "Health · Repair operations · Orphan cleanup",
    href: "/admin/health",
    keywords: "prune reactions orphan note hash cleanup",
    Icon: Smile,
  },
  {
    id: "repair:orphaned-occurrences",
    title: "Prune orphaned ritual occurrences",
    description: "DELs ritual:occurrence:{ritualId}:{dateKey} whose ritual is gone.",
    page: "Diagnostics",
    section: "Health · Repair operations · Orphan cleanup",
    href: "/admin/health",
    keywords: "prune ritual occurrence orphan hash cleanup",
    Icon: CalendarX,
  },
  {
    id: "repair:obedience-drift",
    title: "Repair obedience drift",
    description: "Reconciles obedience:events ↔ obedience:audit ZSETs across current + 4 prior weeks.",
    page: "Diagnostics",
    section: "Health · Repair operations · Obedience",
    href: "/admin/health",
    keywords: "repair obedience drift events audit zset reconcile rewards",
    Icon: ShieldCheck,
  },

  // ── /admin/health (Cooldowns tab) ──────────────────────────────────────
  {
    id: "cooldowns:safeword",
    title: "Safeword cooldowns",
    description: "Per-author 5-min spam shield TTL viewer.",
    page: "Diagnostics",
    section: "Cooldowns",
    href: "/admin/health",
    keywords: "safeword cooldown spam shield ttl 5 minutes",
    Icon: ShieldOff,
  },
  {
    id: "cooldowns:reask",
    title: "Active reask blocks",
    description: "Per-body-hash denial cooldown (12h–168h depending on reason).",
    page: "Diagnostics",
    section: "Cooldowns",
    href: "/admin/health",
    keywords: "reask block permission denial cooldown body hash ttl",
    Icon: Timer,
  },
  {
    id: "cooldowns:denied-hashes",
    title: "Denied hashes set size",
    description: "Lifetime SCARD of permissions:denied-hashes.",
    page: "Diagnostics",
    section: "Cooldowns",
    href: "/admin/health",
    keywords: "denied hashes lifetime permissions previously denied set scard",
    Icon: Filter,
  },

  // ── /admin/health (Time tab) ───────────────────────────────────────────
  {
    id: "time:snapshot",
    title: "Cairo + Tabuk live snapshot",
    description: "Side-by-side wall clock with offsets, weekday, weekKey, rollover.",
    page: "Diagnostics",
    section: "Time",
    href: "/admin/health",
    keywords: "time cairo tabuk timezone offset weekday weekkey rollover",
    Icon: Clock,
  },
  {
    id: "time:converter",
    title: "Cairo ↔ Tabuk converter",
    description: "Visit-planning utility — pick a wall-clock instant, see the other zone.",
    page: "Diagnostics",
    section: "Time",
    href: "/admin/health",
    keywords: "convert cairo tabuk timezone visit planning offset",
    Icon: Clock,
  },

  // ── /admin/trash ───────────────────────────────────────────────────────
  {
    id: "trash:retention",
    title: "Trash retention days",
    description: "Sir-tunable TTL (1–90, default 7). Applies to future deletions only.",
    page: "Trash & restore",
    href: "/admin/trash",
    keywords: "trash retention ttl days 7 90 soft delete",
    Icon: Trash2,
  },
  {
    id: "trash:restore",
    title: "Restore soft-deleted records",
    description: "Per-feature list with multi-select bulk restore.",
    page: "Trash & restore",
    href: "/admin/trash",
    keywords: "trash restore soft delete bulk multi-select recover",
    Icon: Trash2,
  },
  {
    id: "trash:purge",
    title: "Purge trash (per-feature)",
    description: "Permanently delete trashed entries for a feature.",
    page: "Trash & restore",
    href: "/admin/trash",
    keywords: "trash purge permanent delete feature",
    Icon: Eraser,
  },

  // ── /admin/export ──────────────────────────────────────────────────────
  {
    id: "export:snapshot",
    title: "Download JSON snapshot",
    description: "Full export of every feature index + records + system state.",
    page: "Export",
    href: "/admin/export",
    keywords: "export download backup json snapshot dump",
    Icon: Download,
  },

  // ── /admin/devices ─────────────────────────────────────────────────────
  {
    id: "devices:right-now",
    title: "Right now (presence + tokens)",
    description: "Per-author presence freshness + every push:fcm:{author} SET member with masked preview.",
    page: "Devices & sessions",
    href: "/admin/devices",
    keywords: "presence devices fcm token right now live multi device set",
    Icon: Smartphone,
  },
  {
    id: "devices:force-logout",
    title: "Force logout (session epoch)",
    description: "Bumps session:epoch:{author} so existing JWTs reject on next request.",
    page: "Devices & sessions",
    href: "/admin/devices",
    keywords: "force logout session epoch jwt revoke kick out",
    Icon: ZapOff,
  },
  {
    id: "devices:list",
    title: "Per-install device list",
    description: "device:{id} records — last heartbeat, fingerprint, coords (native only).",
    page: "Devices & sessions",
    href: "/admin/devices",
    keywords: "devices list install heartbeat fingerprint coords location",
    Icon: Smartphone,
  },
  {
    id: "devices:forget",
    title: "Forget device",
    description: "Removes a stale device record from the index.",
    page: "Devices & sessions",
    href: "/admin/devices",
    keywords: "forget remove device stale index",
    Icon: Eraser,
  },

  // ── /admin/logs ────────────────────────────────────────────────────────
  {
    id: "logs:activity",
    title: "Activity log",
    description: "Capped 500-entry feed (interaction / warn / error / fatal) with level filter.",
    page: "Logs",
    section: "Activity",
    href: "/admin/logs",
    keywords: "activity log feed audit interaction warn error fatal level filter",
    Icon: Activity,
  },
  {
    id: "logs:activity-clear",
    title: "Clear activity log",
    description: "Wipes activity:log ZSET. Sir-confirmed.",
    page: "Logs",
    section: "Activity",
    href: "/admin/logs",
    keywords: "clear activity log wipe purge",
    Icon: Eraser,
  },
  {
    id: "logs:outbound",
    title: "Outbound notification audit",
    description: "Forward-only Sir-private record of every push fired (cap 200).",
    page: "Logs",
    section: "Outbound",
    href: "/admin/logs",
    keywords: "outbound notifications audit fcm push history resend",
    Icon: Send,
  },
  {
    id: "logs:outbound-resend",
    title: "Resend notification",
    description: "Re-fires a previously-sent push by audit id.",
    page: "Logs",
    section: "Outbound",
    href: "/admin/logs",
    keywords: "resend notification push fcm replay",
    Icon: Send,
  },
  {
    id: "logs:restraint",
    title: "Restraint history",
    description: "Engage / lift audit trail (capped 200) with optional reason note.",
    page: "Logs",
    section: "Restraint",
    href: "/admin/logs",
    keywords: "restraint history audit engage lift toggle besho readonly",
    Icon: ShieldAlert,
  },
  {
    id: "logs:auth-failures",
    title: "Auth failure log",
    description: "Capped 100-entry login failures (ts, ip, ua, passcode length) with IP filter.",
    page: "Logs",
    section: "Auth failures",
    href: "/admin/logs",
    keywords: "auth failures login failed bad passcode ip user agent filter",
    Icon: ShieldAlert,
  },
  {
    id: "logs:auth-clear",
    title: "Clear auth failures",
    description: "Wipes auth:failures ZSET.",
    page: "Logs",
    section: "Auth failures",
    href: "/admin/logs",
    keywords: "clear auth failures wipe purge",
    Icon: Eraser,
  },

  // ── /admin/push-test ───────────────────────────────────────────────────
  {
    id: "push-test:send",
    title: "Send custom push",
    description: "Free-form title / body / url; recipient picker (Daddy / Kitten / Both).",
    page: "Send test push",
    href: "/admin/push-test",
    keywords: "push test fcm send custom notification daddy kitten both recipient",
    Icon: Send,
  },
  {
    id: "push-test:presets",
    title: "12 tap-to-fill presets",
    description: "Curated push presets — 8 to Sir, 3 to Both, 1 to kitten.",
    page: "Send test push",
    href: "/admin/push-test",
    keywords: "push presets templates tap fill quick",
    Icon: Sparkles,
  },

  // ── /admin/directive ───────────────────────────────────────────────────
  {
    id: "directive:issue",
    title: "Issue real-time directive",
    description: "Short-lived command (1–60 min) with countdown overlay on kitten's device.",
    page: "Real-time directive",
    href: "/admin/directive",
    keywords: "directive command real-time overlay countdown kitten besho timer kneel",
    Icon: Target,
  },
  {
    id: "directive:cancel",
    title: "Cancel active directive",
    description: "Single-slot — cancel before issuing a new one.",
    page: "Real-time directive",
    href: "/admin/directive",
    keywords: "directive cancel active stop dismiss",
    Icon: Target,
  },
  {
    id: "directive:history",
    title: "Directive history",
    description: "Last 50 directives with acknowledged / completed / expired state.",
    page: "Real-time directive",
    href: "/admin/directive",
    keywords: "directive history list past completed expired log",
    Icon: Target,
  },

  // ── /admin/punishment-timer ────────────────────────────────────────────
  {
    id: "punishment-timer:issue",
    title: "Issue punishment timer",
    description: "Duration-bounded corrective timer (1–120 min) with full-screen kneel overlay.",
    page: "Punishment timer",
    href: "/admin/punishment-timer",
    keywords: "punishment timer kneel corrective duration overlay besho kitten discipline",
    Icon: AlertTriangle,
  },
  {
    id: "punishment-timer:cancel",
    title: "Cancel active punishment",
    description: "Single-slot — cancel before issuing a new one.",
    page: "Punishment timer",
    href: "/admin/punishment-timer",
    keywords: "punishment cancel active stop dismiss",
    Icon: AlertTriangle,
  },
  {
    id: "punishment-timer:history",
    title: "Punishment history",
    description: "Last 50 punishments with completed / bailed / cancelled state.",
    page: "Punishment timer",
    href: "/admin/punishment-timer",
    keywords: "punishment history list past completed bailed log",
    Icon: AlertTriangle,
  },

  // ── /admin/mood ────────────────────────────────────────────────────────
  {
    id: "mood:override",
    title: "Override mood for an author",
    description: "Force-set or clear today's mood for T7SEN or Besho.",
    page: "Mood override",
    href: "/admin/mood",
    keywords: "mood override set clear today daddy kitten",
    Icon: Smile,
  },
  {
    id: "mood:state-override",
    title: "Override state for an author",
    description: "Force-set or clear today's state badge.",
    page: "Mood override",
    href: "/admin/mood",
    keywords: "state override set clear today daddy kitten badge",
    Icon: Smile,
  },

  // ── /admin/dates ───────────────────────────────────────────────────────
  {
    id: "dates:anniversary",
    title: "Anniversary date",
    description: "Relationship start. Drives counter card + countdown overlay.",
    page: "Anniversary & birthdays",
    href: "/admin/dates",
    keywords: "anniversary relationship start counter date dashboard",
    Icon: CalendarHeart,
  },
  {
    id: "dates:birthday-t7sen",
    title: "T7SEN birthday",
    description: "Sir's birthday — drives the dashboard birthday card.",
    page: "Anniversary & birthdays",
    href: "/admin/dates",
    keywords: "birthday daddy t7sen sir bday",
    Icon: CalendarHeart,
  },
  {
    id: "dates:birthday-besho",
    title: "Besho birthday",
    description: "Kitten's birthday — drives the dashboard birthday card.",
    page: "Anniversary & birthdays",
    href: "/admin/dates",
    keywords: "birthday kitten besho bday",
    Icon: CalendarHeart,
  },

  // ── /admin/rewards ─────────────────────────────────────────────────────
  {
    id: "rewards:tiers",
    title: "Reward tiers",
    description: "5-tier ladder editor. Names, thresholds, emoji, catalog items per tier.",
    page: "Rewards & obedience",
    section: "Tiers",
    href: "/admin/rewards",
    keywords: "rewards tiers thresholds catalog emoji medal trophy crown 5",
    Icon: Trophy,
  },
  {
    id: "rewards:weights",
    title: "Obedience weights",
    description: "Points per event type — task, rule, ritual, permission, restraint, mood, manual.",
    page: "Rewards & obedience",
    section: "Weights",
    href: "/admin/rewards",
    keywords: "obedience weights points event types weights config score",
    Icon: Gauge,
  },
  {
    id: "rewards:streak",
    title: "Streak threshold + multipliers",
    description: "High-score threshold (default 80) and per-streak multiplier ladder (×1.0 / ×1.1 / ×1.2 / ×1.3).",
    page: "Rewards & obedience",
    section: "Streak",
    href: "/admin/rewards",
    keywords: "streak threshold multiplier high score 80 weeks consecutive",
    Icon: Sparkles,
  },
  {
    id: "rewards:streak-raw",
    title: "Override streak count (raw)",
    description: "Sir-only forced reset of obedience:streak:{author}.",
    page: "Rewards & obedience",
    section: "Streak",
    href: "/admin/rewards",
    keywords: "streak override reset raw force besho",
    Icon: Wand2,
  },
  {
    id: "rewards:streak-risk",
    title: "Streak-risk min deficit",
    description: "How many points behind threshold before the Friday FCM fires.",
    page: "Rewards & obedience",
    section: "Streak",
    href: "/admin/rewards",
    keywords: "streak risk friday fcm deficit notification nudge",
    Icon: Bell,
  },
  {
    id: "rewards:test-mode",
    title: "Test mode toggle",
    description: "Opens current-week claims for diagnostic flow verification. Streak/multiplier untouched.",
    page: "Rewards & obedience",
    section: "Status",
    href: "/admin/rewards",
    keywords: "test mode rewards claim verify diagnostic flow",
    Icon: FlaskConical,
  },
  {
    id: "rewards:simulator",
    title: "Score simulator",
    description: "Pure-client what-if calculator for tier outcomes given a score.",
    page: "Rewards & obedience",
    section: "Status",
    href: "/admin/rewards",
    keywords: "simulator simulate what if score tier outcome",
    Icon: FlaskConical,
  },
  {
    id: "rewards:manual-adjust",
    title: "Manual adjust score",
    description: "Sir-only ad-hoc points with reason — records as `manual_adjust` event with optional FCM.",
    page: "Rewards & obedience",
    section: "Status",
    href: "/admin/rewards",
    keywords: "manual adjust score points reason award fcm notify ad hoc",
    Icon: Wand2,
  },
  {
    id: "rewards:purge-test-claims",
    title: "Purge test claims",
    description: "Wipes any reward claims tagged testMode=true.",
    page: "Rewards & obedience",
    section: "Status",
    href: "/admin/rewards",
    keywords: "purge test claims wipe rewards diagnostic",
    Icon: Eraser,
  },
  {
    id: "rewards:event-log",
    title: "Event log viewer",
    description: "Per-week obedience events with sign / type filters + pagination.",
    page: "Rewards & obedience",
    section: "Event log",
    href: "/admin/rewards",
    keywords: "event log obedience audit history filter pagination week",
    Icon: ScrollText,
  },
  {
    id: "rewards:delete-event",
    title: "Delete obedience event",
    description: "Per-row event deletion (events ZSET + audit ZSET + reason HASH for manual).",
    page: "Rewards & obedience",
    section: "Event log",
    href: "/admin/rewards",
    keywords: "delete event obedience audit row remove",
    Icon: Trash2,
  },
  {
    id: "rewards:recompute-week",
    title: "Recompute week",
    description: "Forces recomputation of an obedience week (for repair after manual mutation).",
    page: "Rewards & obedience",
    section: "Status",
    href: "/admin/rewards",
    keywords: "recompute week obedience force repair manual recalc",
    Icon: RefreshCw,
  },

  // ── /admin/permissions ─────────────────────────────────────────────────
  {
    id: "perm:bulk-approve",
    title: "Bulk approve pending older than…",
    description: "Approve all pending permission requests older than N hours in one shot.",
    page: "Permissions admin",
    section: "Bulk decide",
    href: "/admin/permissions",
    keywords: "bulk approve pending older than mass batch permission",
    Icon: ShieldCheck,
  },
  {
    id: "perm:bulk-deny",
    title: "Bulk deny pending by category",
    description: "Deny all pending permission requests in a category with optional reply.",
    page: "Permissions admin",
    section: "Bulk decide",
    href: "/admin/permissions",
    keywords: "bulk deny pending category mass batch permission",
    Icon: ShieldOff,
  },
  {
    id: "perm:auto-rules",
    title: "Auto-rules JSON editor",
    description: "Sir-private auto-decide ruleset. Validated server-side.",
    page: "Permissions admin",
    section: "Auto-rules",
    href: "/admin/permissions",
    keywords: "auto rules json editor decide automatic permissions sir private",
    Icon: ScrollText,
  },
  {
    id: "perm:quotas",
    title: "Quotas JSON editor",
    description: "Per-category daily / weekly / monthly caps.",
    page: "Permissions admin",
    section: "Quotas",
    href: "/admin/permissions",
    keywords: "quotas json daily weekly monthly cap permissions limit",
    Icon: Gauge,
  },
  {
    id: "perm:simulate",
    title: "Auto-rules simulator",
    description: "Run a fake permission request against the current auto-rules to preview the outcome.",
    page: "Permissions admin",
    section: "Simulate",
    href: "/admin/permissions",
    keywords: "simulate auto rules permission preview what if",
    Icon: FlaskConical,
  },

  // ── /admin/redis ───────────────────────────────────────────────────────
  {
    id: "redis:inspect",
    title: "Redis key inspector",
    description: "Read-only probe by exact key — type, TTL, capped preview. Never mutates.",
    page: "Redis inspector",
    href: "/admin/redis",
    keywords: "redis inspector read only probe key type ttl preview upstash",
    Icon: Server,
  },

  // ── Top-of-/admin landing controls ─────────────────────────────────────
  {
    id: "landing:summon",
    title: "Summon kitten",
    description: "Sir → Besho push that bypasses presence (safeword-style channel + max priority).",
    page: "Admin landing",
    href: "/admin",
    keywords: "summon kitten besho push bypass presence safeword channel possessive",
    Icon: Bell,
  },
  {
    id: "landing:restraint",
    title: "Restraint mode toggle",
    description: "Sir-only flag that makes Besho-writable actions read-only. Safeword stays callable.",
    page: "Admin landing",
    href: "/admin",
    keywords: "restraint mode read only besho toggle lock chastity",
    Icon: ShieldOff,
  },
  {
    id: "landing:recent-actions",
    title: "Recent admin actions",
    description: "Latest Sir-driven mutations across the admin surface.",
    page: "Admin landing",
    href: "/admin",
    keywords: "recent admin actions audit timeline log",
    Icon: LogsIcon,
  },
  {
    id: "landing:dashboard",
    title: "Dashboard strip",
    description: "Pending permissions / pending claims / cron freshness / errors-24h at-a-glance.",
    page: "Admin landing",
    href: "/admin",
    keywords: "dashboard strip pending permissions claims cron errors 24h glance",
    Icon: Gauge,
  },
  {
    id: "landing:deploy-info",
    title: "Deploy info footer",
    description: "Version, commit SHA, branch, env, deploy id, server time.",
    page: "Admin landing",
    href: "/admin",
    keywords: "deploy info version commit sha branch env vercel server time",
    Icon: Pin,
  },
  {
    id: "landing:rewards",
    title: "Rewards & obedience",
    description: "Tier catalog, weights, streak threshold, multipliers, manual adjust.",
    page: "Admin landing",
    href: "/admin/rewards",
    keywords: "rewards obedience tiers catalog weights streak multipliers manual adjust score",
    Icon: Award,
  },
  {
    id: "landing:diagnostics",
    title: "Diagnostics",
    description: "Health, cooldowns, time, repair operations.",
    page: "Admin landing",
    href: "/admin/health",
    keywords: "diagnostics health cooldowns time repair",
    Icon: HeartPulse,
  },
];
