import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Capacitor Android platform — native project + Gradle build
    // output. Regenerated by `cap sync` / Gradle builds and gitignored;
    // the minified `sw.js` / `native-bridge.js` under android/app/build/
    // are bundled artifacts, not lintable web source. The root-level
    // `build/**` above does not match this nested path.
    "android/**",
  ]),
]);

export default eslintConfig;
